channels: 
  - defaults 
  - conda-forge 
  - anaconda 
dependencies: 
  - babel=2.11.0 
  - blas=1.0 
  - boost-cpp=1.82.0 
  - bzip2=1.0.8 
  - cairo=1.16.0 
  - graphite2=1.3.14 
  - graphviz=2.50.0 
  - jupyter_client=7.4.9 
  - jupyter_core=5.7.2 
  - jupyter_server=1.23.4 
  - jupyterlab_pygments=0.2.2 
  - jupyterlab_server=2.22.0 
  - kiwisolver=1.4.4 
  - matplotlib-base=3.6.0 
  - notebook=6.5.7 
  - notebook-shim=0.2.3 
  - numpy=1.26.4 
  - python=3.10.13 
  - statannotations=0.7.1 
  - statsmodels=0.13.2 
  - tabulate=0.9.0 
  - pip 
  - pip: 
    - beautifulsoup4==4.11.1 
    - bleach==4.1.0 
    - cachetools==5.3.0 
    - caveclient==5.21.0 
    - cloudpickle==2.2.1 
    - contourpy==1.0.7 
    - dill==0.3.5.1 
    - docutils==0.19 
    - dotmotif==0.14.0 
    - factor-analyzer==0.5.1 
    - fastprogress==1.0.3 
    - h5netcdf==1.1.0 
    - h5py==3.8.0 
    - imbalanced-learn==0.12.3 
    - ipykernel==6.21.2 
    - ipython==8.10.0 
    - ipython-genutils==0.2.0 
    - jupyter-client==8.0.3 
    - jupyter-core==5.2.0 
    - jupyterlab==3.4.7 
    - jupytext==1.14.1 
    - matplotlib==3.7.0 
    - networkx==3.2.1 
    - neuroanalysistools
    - pandas==2.2.1 
    - pillow==9.4.0 
    - pip==22.2.2 
    - ptitprince==0.2.7 
    - scikit-image==0.22.0 
    - scikit-learn==1.5.2 
    - scipy==1.10.1 
    - seaborn==0.11.0 
    - sklearn==0.0.post1 
    - standard-transform==1.4.0 
    - tifffile==2024.2.12 
    - v1dd-physiology
    - xarray==2023.2.0 
    - xarray-einstats==0.5.1 
